[platformio]
default_envs = esp32-c3

[common]
board_build.filesystem = littlefs
monitor_host = gps.fritz.box
monitor_port = 23

build_flags =
    -O2
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ASYNC_TCP_SSL_ENABLED=0
    -D CONFIG_ASYNC_TCP_STACK_SIZE=8192
    -fno-exceptions
    -freorder-blocks
    -fschedule-insns
    -fschedule-insns2
    -D ENABLE_OTA
    -D LED=8
    -D LED_INVERTED

build_src_flags =
    -Os
    -ffast-math
    -Wall
    -Wextra
    -Wno-missing-field-initializers
    -Wno-unused-function
    -Wdouble-promotion
    -Wpointer-arith
    -Wmaybe-uninitialized
    -Wsign-compare
    -Wfloat-equal
    -Wcast-align
    -Wunreachable-code
    -Wstrict-overflow=5
    -Wformat=2
    -D LAST_BUILD_TIME=$UNIX_TIME

[env:esp32-c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = nologo_esp32c3_super_mini
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_dtr = 1
monitor_rts = 1

lib_deps =
    bblanchon/ArduinoJson
    mikalhart/TinyGPSPlus
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    FrankBoesing/AsyncTelnet

build_flags =
    ${common.build_flags}
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG

build_src_flags =
    ${common.build_src_flags}

[env:esp32-c3-release]
extends = env:esp32-c3
build_type = release

build_unflags =
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG

build_flags =
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN
    -D NDEBUG

[env:esp32-c3-ota]
extends = env:esp32-c3
upload_protocol = espota
upload_port = gps.fritz.box
upload_flags =
    --port=3232
    --host_port=20000

[env:esp32-c3-release-ota]
extends = env:esp32-c3-release
upload_protocol = espota
upload_port = gps.fritz.box
upload_flags =
    --port=3232
    --host_port=20000
