; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c3

[common]
board_build.filesystem = littlefs

# Flags, die generell entfernt werden sollen
build_unflags =
	-D CONFIG_BOOTLOADER_LOG_LEVEL

# Allgemeine Build-Flags
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CONFIG_BOOTLOADER_LOG_LEVEL=0
	-D CONFIG_ARDUHAL_LOG_COLORS=1
	-D ASYNC_TCP_SSL_ENABLED=0
	-D CONFIG_ASYNC_TCP_STACK_SIZE=8192

# Warnungen / Compiler Flags für Quellcode
build_src_flags =
	-Wall
	-Wextra
	-D LAST_BUILD_TIME=$UNIX_TIME

# ----------------------------------------
# Debug / normale Umgebung
[env:esp32-c3]

platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = nologo_esp32c3_super_mini
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_dtr = 1
monitor_rts = 1

lib_deps =
	bblanchon/ArduinoJson
	mikalhart/TinyGPSPlus
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	https://github.com/FrankBoesing/AsyncTelnet
lib_compat_mode = strict
lib_ldf_mode = chain

build_unflags = ${common.build_unflags}
build_flags =
	${common.build_flags}
	-D ENABLE_OTA

build_src_flags =
	${common.build_src_flags}
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
	-D LED=8
	# Extra Warnings
	-Wno-missing-field-initializers
	-Wno-unused-function
	-Wdouble-promotion
	-Wpointer-arith
	-Wmaybe-uninitialized
	-Wsign-compare
	-Wfloat-equal
	-Wcast-align
	-Wunreachable-code
	-Wstrict-overflow=5
	-Wformat=2
	# ESP32-C3 Performance Flags (Debug)
	-O2
	-march=rv32imc
	-mabi=ilp32
	-ffast-math
	-fno-exceptions
	-fno-rtti
	-freorder-blocks
	-ffunction-sections
	-fdata-sections
	-fschedule-insns
	-fschedule-insns2

# ----------------------------------------
# Release-Build (maximale Geschwindigkeit)
[env:esp32-c3-release]
extends = env:esp32-c3
build_type = release

# Entfernt Debug-Log-Level Flags
build_unflags =
	${common.build_unflags}
	-D CORE_DEBUG_LEVEL

build_flags =
	${common.build_flags}
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN
	-D NDEBUG
	-D ENABLE_OTA
build_src_flags =
	${common.build_src_flags}
	-D LED=8
	# ESP32-C3 Performance Flags (Release)
	-O2
	-march=rv32imc
	-mabi=ilp32
	-ffast-math
	-fno-exceptions
	-fno-rtti
	-fno-stack-protector
	-freorder-blocks
	-ffunction-sections
	-fdata-sections
	-fschedule-insns
	-fschedule-insns2

[env:esp32-c3-ota]
extends = env:esp32-c3
build_type = release

upload_protocol = espota
upload_port = 192.168.178.61
upload_flags =
  --port=3232
  --host_port=20000
#upload_command = "$PROJECT_PACKAGES_DIR/tool-esptool/esptool.exe" -cf $SOURCE
